[package]
name = "rust"
version = "1.0.1"
authors = ["Zingolabs <zingo@zingolabs.com>"]
edition = "2021"

[dependencies]
jni = { version = "0.19.0", default-features = false }
android_logger = "0.11"
log = { workspace = true }
rustlib = { path = "../lib" }

[dev-dependencies]
tokio =  { version = "1.24.2", features = ["full"] }
zingo-testutils = { git="https://github.com/zingolabs/zingolib", default-features=true, branch = "dev" }
env_logger = "*"

[lib]
crate-type = ["dylib"]

[features]
default = ["local_env"]
local_env = []

