[package]
name = "rust"
version = "1.0.1"
authors = ["Aditya Kulkarni <aditya@zecwallet.co>", "Zingolabs <zingo@zingolabs.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = { version = "0.19", default-features = false }
android_logger = "0.11"
log = "0.4"
rustlib = { path = "../lib" }

[lib]
crate-type = ["cdylib"]