[package]
name = "rust"
version = "1.0.1"
authors = ["Zingolabs <zingo@zingolabs.com>"]
edition = "2021"

[features]
ci = []

[dependencies]
jni = { version = "0.19.0", default-features = false }
android_logger = "0.11"
log = { workspace = true }
rustlib = { path = "../lib" }

[dev-dependencies]
tokio =  { version = "1.24.2", features = ["full"] }
zingo-testutils = { git="https://github.com/zingolabs/zingolib", default-features=true, branch = "dev" }
json = "0.12.4"
env_logger = "0.10.0"
zingomobile_utils = { path = "../zingomobile_utils" }
regchest_utils = { git="https://github.com/Oscar-Pepper/zingo-regchest", default-features=true, branch = "launch_regtest" }

[lib]
crate-type = ["dylib"]

