[workspace]
members = [
    "lib",
    "android",
    "ios",
    "test_utils"
]

[workspace.dependencies]
log = "0.4.8"
zingolib = { git="https://github.com/zingolabs/zingolib", default-features=true, branch = "dev" }
zingoconfig = { git="https://github.com/zingolabs/zingolib", default-features=true, branch = "dev" }

[profile.release]
debug = false

[profile.test]
opt-level = 3
debug = false

[patch.crates-io]
zcash_note_encryption = { git = "https://github.com/zingolabs/librustzcash", rev = "fa67d9a645da55265ebea8cedbb77ff42317c726" }
zcash_primitives = { git = "https://github.com/zingolabs/librustzcash", rev = "fa67d9a645da55265ebea8cedbb77ff42317c726" }
