[workspace]
members = [
    "lib",
    "android",
    "ios",
    "test_utils"
]
resolver = "2"

[workspace.dependencies]
log = "0.4.8"
zingolib = { git="https://github.com/zingolabs/zingolib", default-features=true, branch = "dev" }
zingoconfig = { git="https://github.com/zingolabs/zingolib", default-features=true, branch = "dev" }

[profile.release]
debug = false

[profile.test]
opt-level = 3
debug = false

[patch.crates-io]
zcash_primitives = { git = "https://github.com/nuttycom/librustzcash.git", rev = "669e0797bff3b506984bd2851b22d9eae40a758a" }
zcash_address = { git = "https://github.com/nuttycom/librustzcash.git", rev = "669e0797bff3b506984bd2851b22d9eae40a758a" }
