[workspace]
members = [
    "lib",
    "android",
    "ios",
    "zingomobile_utils"
]
resolver = "2"

[workspace.dependencies]
log = "0.4.8"
zingolib = { git="https://github.com/zingolabs/zingolib", default-features=true, branch = "dev" }
zingoconfig = { git="https://github.com/zingolabs/zingolib", default-features=true, branch = "dev" }

[profile.release]
debug = false

[profile.test]
opt-level = 3
debug = false

[patch.crates-io]
zcash_primitives = { git = "https://github.com/zcash/librustzcash.git", branch = "release-lwsdk-2.0.0" }
zcash_address = { git = "https://github.com/zcash/librustzcash.git", branch = "release-lwsdk-2.0.0" }
