[workspace]
members = [
    "lib",
    "android",
    "ios"
]

[profile.release]
debug = false

# [target.'cfg(target_arch = "i686")'.dependencies]
[patch.crates-io]
bellman = { git = "https://github.com/dannasessha/bellman", rev="675ca9a", default-features=false, features = ["groth16"] }