[workspace]
members = [
    "lib",
    "android",
    "ios",
    "zingomobile_utils"
]
resolver = "2"

[workspace.dependencies]
log = "0.4.8"
zingolib = { git="https://github.com/Oscar-Pepper/zingolib", default-features=true, branch = "regtest_network_upgrade_activation_heights" }
zingoconfig = { git="https://github.com/Oscar-Pepper/zingolib", default-features=true, branch = "regtest_network_upgrade_activation_heights" }
# zingolib = { git="https://github.com/zingolabs/zingolib", default-features=true, branch = "dev" }
# zingoconfig = { git="https://github.com/zingolabs/zingolib", default-features=true, branch = "dev" }

[profile.release]
debug = false

[profile.test]
opt-level = 3
debug = false
