[workspace]
members = [
    "lib",
    "android",
    "ios"
]

[profile.release]
debug = false

[patch.crates-io]
bellman = { git = "https://github.com/zingolabs/bellman", rev="c852464b1743d10072ab0521fba939f79da6798e" }
