[workspace]
members = [
    "lib",
    "android",
    "ios",
    "test_utils"
]

[workspace.dependencies]
log = "0.4.8"
zingolib = { git="https://github.com/Oscar-Pepper/zingolib", default-features=true, branch = "add_mobile_funded_orchard_scenario" }
zingoconfig = { git="https://github.com/Oscar-Pepper/zingolib", default-features=true, branch = "add_mobile_funded_orchard_scenario" }

[profile.release]
debug = false

[patch.crates-io]
zcash_note_encryption = { git = "https://github.com/zingolabs/librustzcash", rev = "acfdabc3629c93517e3c4742848996c595de6d3c" }
zcash_primitives = { git = "https://github.com/zingolabs/librustzcash", rev = "acfdabc3629c93517e3c4742848996c595de6d3c" }
