[workspace]
members = [
    "lib",
    "android",
    "ios",
    "zingomobile_utils"
]
resolver = "2"

[workspace.dependencies]
log = "0.4.8"
zingolib = { git="https://github.com/Oscar-Pepper/zingolib", default-features=true, branch = "add_interrupt_sync_test" }
zingoconfig = { git="https://github.com/Oscar-Pepper/zingolib", default-features=true, branch = "add_interrupt_sync_test" }

[profile.release]
debug = false

[profile.test]
opt-level = 3
debug = false
