name: CI

on:
  pull_request:
  push:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  jest-test:
    uses: Oscar-Pepper/zingo-mobile/.github/workflows/jest-test.yaml@ci_DRY
    
  create-timestamp:
    uses: Oscar-Pepper/zingo-mobile/.github/workflows/create-timestamp.yaml@ci_DRY
    
  build:
    uses: Oscar-Pepper/zingo-mobile/.github/workflows/build.yaml@ci_DRY
       
  integration-test:
    uses: Oscar-Pepper/zingo-mobile/.github/workflows/integration-test.yaml@ci_DRY
    needs: [ create-timestamp, build ]
    if: ${{ ! cancelled() }}
    with:
      timestamp: ${{ needs.create-timestamp.outputs.timestamp }}
      cache-key: ${{ needs.build.outputs.cache-key }}
  
  e2e-test:
    uses: Oscar-Pepper/zingo-mobile/.github/workflows/e2e-test.yaml@ci_DRY
    needs: build
    if: ${{ ! cancelled() }}
    with:
      cache-key: ${{ needs.build.outputs.cache-key }}
