name: CI

on:
  pull_request:
  push:
    branches: [main, dev]

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - run: yarn install
      
      - name: Run tests
        run: yarn test
  
  create_timestamp:
    name: Create timestamp
    runs-on: ubuntu-22.04
    outputs:
      timestamp: ${{ steps.create_timestamp.outputs.timestamp }}
    steps:
      - name: Create timestamp
        id: create_timestamp
        run: echo "timestamp=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
  
  create_cache_key:
    name: Create cache key
    runs-on: ubuntu-22.04
    container:
      image: zingodevops/android_builder:stable
    env:
      RUSTUP_HOME: /root/.rustup
    outputs:
      cache_key: ${{ steps.create_cache_key.outputs.cache_key }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Store Cargo version
        run: echo $(cargo --version) >> rust/cargo_version.txt
      
      - name: Create cache key
        id: create_cache_key
        run: echo "cache_key=${{ hashFiles('rust/**/Cargo.toml', 'rust/**/Cargo.lock', 'rust/**/*.rs', 'rust/cargo_version.txt') }}" >> $GITHUB_OUTPUT
  
  check_build_cache:
    name: Check build cache
    needs: create_cache_key
    runs-on: macos-12
    env:
      cache_key: ${{ needs.create_cache_key.outputs.cache_key }}
    outputs:
      status_x86: ${{ steps.set_output_status.outputs.status_x86 }}
      status_x86_64: ${{ steps.set_output_status.outputs.status_x86_64 }}
      status_armeabi-v7a: ${{ steps.set_output_status.outputs.status_armeabi-v7a }}
      status_arm64-v8a: ${{ steps.set_output_status.outputs.status_arm64-v8a }}
    strategy:
      matrix:
        abi: [x86, x86_64, armeabi-v7a, arm64-v8a]
      fail-fast: false
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
           
      - name: Check if native rust cache exists
        id: check_build_cache
        uses: actions/cache@v3
        with:
          path: android/app/src/main/jniLibs/${{ matrix.abi }}
          key: native-rust-${{ matrix.abi }}-${{ env.cache_key }}
          lookup-only: true
          fail-on-cache-miss: true
  
      - name: Set output status
        id: set_output_status
        if: ${{ ! cancelled() }}
        run: echo "status_${{ matrix.abi }}=${{ steps.check_build_cache.outcome }}" >> $GITHUB_OUTPUT
  
  build:
    name: Build native rust (${{ matrix.abi }})
    needs: [create_cache_key, check_build_cache]
    if: ${{ contains(needs.*.outputs.*, 'failure') }}
    runs-on: ubuntu-22.04
    container:
      image: zingodevops/android_builder:stable
    env:
      cache_key: ${{ needs.create_cache_key.outputs.cache_key }}
      RUSTUP_HOME: /root/.rustup
    strategy:
      matrix:
        include:
          - abi: x86
            target: i686-linux-android
            cc: i686-linux-android
            openssl_path: x86
          - abi: x86_64
            target: x86_64-linux-android
            cc: x86_64-linux-android
            openssl_path: x86_64
          - abi: armeabi-v7a
            target: armv7-linux-androideabi
            cc: armv7a-linux-androideabi
            openssl_path: armv7
          - abi: arm64-v8a
            target: aarch64-linux-android
            cc: aarch64-linux-android
            openssl_path: aarch64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Cargo cache
        id: cargo_cache
        uses: actions/cache@v3
        with:
          # TODO: ref paths from cargo
          path: |
            /root/.cargo/.crates.toml
            /root/.cargo/.crates2.json
            /root/.cargo/bin/
            /root/.cargo/registry/index/            
            /root/.cargo/registry/cache/
            /root/.cargo/registry/git/db/
          key: cargo-${{ matrix.abi }}-${{ hashFiles('rust/Cargo.lock') }}
          restore-keys: cargo-${{ matrix.abi }}
      
      - name: Cargo build
        working-directory: ./rust/android
        run: cargo +nightly build -Z build-std --target ${{ matrix.target }} --release
        env:
          AR: llvm-ar
          LD: ld
          RANLIB: llvm-ranlib
          CC: ${{ matrix.cc }}23-clang
          OPENSSL_DIR: /opt/openssl-3.0.5/${{ matrix.openssl_path }}
      
      - name: LLVM Strip
        working-directory: ./rust/target
        run: llvm-strip ./${{ matrix.target }}/release/librust.so
      
      - name: Upload native rust
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.abi }}-${{ env.cache_key }}
          path: rust/target/${{ matrix.target }}/release/librust.so
      
  cache_native_rust:
    name: Cache native rust
    needs: [create_cache_key, build]
    runs-on: macos-12
    env:
      cache_key: ${{ needs.create_cache_key.outputs.cache_key }}
    strategy:
      matrix:
        abi: [x86, x86_64, armeabi-v7a, arm64-v8a]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Download native rust
        uses: actions/download-artifact@v3
        with: 
          name: ${{ matrix.abi }}-${{ env.cache_key }}
          path: android/app/src/main/jniLibs/${{ matrix.abi }}
      
      - name: Cache native rust
        uses: actions/cache@v3
        with:
          path: android/app/src/main/jniLibs/${{ matrix.abi }}
          key: native-rust-${{ matrix.abi }}-${{ env.cache_key }}
  
  integration_test:
    name: Integration test
    needs: [create_cache_key, cache_native_rust]
    if: ${{ ! cancelled() }}
    runs-on: macos-12
    defaults:
      run:
        shell: bash
    env:
      cache_key: ${{ needs.create_cache_key.outputs.cache_key }}
    strategy:
      matrix:
        include:
          - abi: x86
            avd: x86
            api-level: 30
          - abi: x86_64
            avd: x86_64
            api-level: 30
          - abi: arm64-v8a
            avd: x86_64
            api-level: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      
      - name: Add emulator to PATH
        run: echo "${ANDROID_SDK_ROOT}/emulator" >> $GITHUB_PATH
            
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3.3
          build-root-directory: ./android
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dev' }}
      
      - name: AVD cache
        uses: actions/cache@v3
        id: avd_cache
        with: 
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.avd }}-api-${{ matrix.api-level }}-integ # will remove 'integ' once e2e is synced
          
      - name: Native rust cache
        uses: actions/cache@v3
        with:
          path: android/app/src/main/jniLibs/${{ matrix.abi }}
          key: native-rust-${{ matrix.abi }}-${{ env.cache_key }}
          fail-on-cache-miss: true
      
      - run: yarn install
      
      - name: Create AVD and generate snapshot for caching
        if: steps.avd_cache.outputs.cache-hit != 'true'
        run: ./scripts/integration_tests.sh -a ${{ matrix.avd }} -s

      - name: Run integration tests
        run: ./scripts/integration_tests.sh -a ${{ matrix.abi }}
 
  e2e_test:
    name: End-to-End Test
    if: ${{ ! cancelled() }}
    runs-on: macos-12
    strategy:
      matrix:
        arch: [x86_64]
        api-level: [30]
    needs: [create_timestamp, build]
    env:
      timestamp: ${{ needs.create_timestamp.outputs.timestamp }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3.3
          build-root-directory: ./android
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dev'}}
      
      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with: 
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.arch }}-api-${{ matrix.api-level }}      

      - name: Download native rust
        uses: actions/download-artifact@v3
        with: 
          name: ${{ matrix.arch }}-${{ env.timestamp }}
          path: android/app/src/main/jniLibs/${{ matrix.arch }}
      
      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
      
      - run: yarn install
      - run: nohup yarn react-native start > "out.yarn_react_native_start" &
      
      - name: Run Detox Build
        run: yarn detox build -c android.emu.debug -n test
      
      - name: Run Detox Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: yarn detox test -c android.emu.debug -n test

