name: CI

on:
  pull_request:
  push:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  jest-test:
    uses: Oscar-Pepper/zingo-mobile/.github/workflows/jest-test.yaml@ci_DRY
    
  create-timestamp:
    uses: Oscar-Pepper/zingo-mobile/.github/workflows/create-timestamp.yaml@ci_DRY
    
  create-cache-key:
    uses: Oscar-Pepper/zingo-mobile/.github/workflows/create-cache-key.yaml@ci_DRY
    
  build:
    strategy:
      matrix:
        arch: [ x86_64, armeabi-v7a ]
    uses: Oscar-Pepper/zingo-mobile/.github/workflows/build.yaml@ci_DRY
    needs: create-cache-key
    with:
      cache-key: ${{ needs.create-cache-key.outputs.cache-key }}
      arch: ${{ matrix.arch }}
       
  integration-test:
    uses: Oscar-Pepper/zingo-mobile/.github/workflows/integration-test.yaml@ci_DRY
    needs: [ create-timestamp, create-cache-key, build ]
    if: ${{ ! cancelled() }}
    with:
      timestamp: ${{ needs.create-timestamp.outputs.timestamp }}
      cache-key: ${{ needs.create-cache-key.outputs.cache-key }}
      abi: armeabi-v7a
  
  # e2e-test:
  #   uses: Oscar-Pepper/zingo-mobile/.github/workflows/e2e-test.yaml@ci_DRY
  #   needs: [ create-cache-key, build ]
  #   if: ${{ ! cancelled() }}
  #   with:
  #     cache-key: ${{ needs.create-cache-key.outputs.cache-key }}
