name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  Build:
    runs-on:                 ubuntu-22.04
    outputs:
      timestamp:             ${{ steps.create-timestamp.outputs.timestamp }}
    steps:
      - id:                  create-timestamp
        run:                 echo "timestamp=$(date +%Y%m%d%H%M)" >> $GITHUB_OUTPUT
      - name:                Checkout repository
        uses:                actions/checkout@v3
      - name:                Build NDK
        run:                 cd rust && ./build.sh
      - name:                Upload native rust
        uses:                actions/upload-artifact@v3
        with:
          name:              jniLibs-${{ steps.create-timestamp.outputs.timestamp }}
          path:              android/app/src/main/jniLibs/
  
  Integration_Test:
    runs-on:                 macos-12
    needs:                   Build
    env:
      timestamp:             ${{ needs.Build.outputs.timestamp }}
    steps:
      - name:                Checkout repository
        uses:                actions/checkout@v3
      - run:                 mkdir android/app/src/main/jniLibs
      - name:                Download native rust
        uses:                actions/download-artifact@v3
        with:                
          name:              jniLibs-${{ env.timestamp }}
          path:              android/app/src/main/jniLibs/
      - run:                 ls -R android/app/src/main/
  
  Test:
    runs-on:                 ubuntu-22.04
    steps:
      - name:                Checkout repository
        uses:                actions/checkout@v3
      - run:                 yarn install
      - name:                Run tests
        run:                 yarn test