name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  Build:
    runs-on:                 ubuntu-22.04
    steps:
      - name:                Checkout repository
        uses:                actions/checkout@v3
      - name:                Build NDK
        run:                 cd rust && ./build.sh
  
  Test:
    runs-on:                 ubuntu-22.04
    steps:
      - name:                Checkout repository
        uses:                actions/checkout@v3
      - run:                 yarn install
      - name:                Run tests
        run:                 yarn test