name: CI

on:
  pull_request:
  push:
    branches: [main, dev]

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - run: yarn install
      
      - name: Run tests
        run: yarn test
  
  create-timestamp:
    name: Create timestamp
    runs-on: ubuntu-22.04
    outputs:
      timestamp: ${{ steps.create-timestamp.outputs.timestamp }}
    steps:
      - name: Create timestamp
        id: create-timestamp
        run: echo "timestamp=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
  
  check_rust_hash:
    name: Check rust hash
    runs-on: ubuntu-22.04
    continue-on-error: true
    outputs:
      status: ${{ steps.check-cache.outcome }}
    strategy:
      matrix:
        abi: [x86, x86_64, armeabi-v7a, arm64-v8a]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Check if native rust cache exists
        id: check-cache
        uses: actions/cache@v3
        with:
          path: rust/target/${{ matrix.abi }}/release/librust.so
          key: native-rust-${{ matrix.abi }}-${{ hashFiles('**/Cargo.toml', '**/Cargo.lock', '**/*.rs') }}
          lookup-only: true
          fail-on-cache-miss: true
  
  debug:
    needs: check_rust_hash
    if: ${{ always() }}
    runs-on: ubuntu-22.04
    steps:
      - name: print all output statuses
        env:
          OUT_STAT: ${{ toJson(needs.*.outputs.status) }}
        run: echo "$OUT_STAT"
      
      - name: print true if one check hash failed
        run: echo ${{ contains(needs.*.outputs.status, 'failure') }}

  build:
    name: Build native rust (${{ matrix.abi }})
    needs: check_rust_hash
    if: ${{ contains(needs.*.outputs.status, 'failure') }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - abi: x86
            target: i686-linux-android
            cc: i686-linux-android
            openssl_path: x86
          - abi: x86_64
            target: x86_64-linux-android
            cc: x86_64-linux-android
            openssl_path: x86_64
          - abi: armeabi-v7a
            target: armv7-linux-androideabi
            cc: armv7a-linux-androideabi
            openssl_path: armv7
          - abi: arm64-v8a
            target: aarch64-linux-android
            cc: aarch64-linux-android
            openssl_path: aarch64
    env:
      RUSTUP_HOME: /root/.rustup
    container:
      image: zingodevops/android_builder:stable
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Cargo cache
        id: cargo-cache
        uses: actions/cache@v3
        with:
          # TODO: ref paths from cargo
          path: |
            /root/.cargo/.crates.toml
            /root/.cargo/.crates2.json
            /root/.cargo/bin/
            /root/.cargo/registry/index/            
            /root/.cargo/registry/cache/
            /root/.cargo/registry/git/db/
          key: cargo-${{ matrix.abi }}-${{ hashFiles('rust/Cargo.lock') }}
          restore-keys: cargo-${{ matrix.abi }}
      
      - name: Cargo build
        working-directory: ./rust/android
        run: cargo +nightly build -Z build-std --target ${{ matrix.target }} --release
        env:
          AR: llvm-ar
          LD: ld
          RANLIB: llvm-ranlib
          CC: ${{ matrix.cc }}23-clang
          OPENSSL_DIR: /opt/openssl-3.0.5/${{ matrix.openssl_path }}
      
      - name: LLVM Strip
        working-directory: ./rust/target
        run: llvm-strip ./${{ matrix.target }}/release/librust.so
      
      - name: Move native rust to jniLibs
        run: |
          mkdir -p android/app/src/main/jniLibs/${{ matrix.abi }}
          mv rust/target/${{ matrix.target }}/release/librust.so android/app/src/main/jniLibs/${{ matrix.abi }}
      
      - name: Native rust cache
        id: native-rust-cache
        uses: actions/cache@v3
        with:
          path: android/app/src/main/jniLibs/${{ matrix.abi }}
          key: native-rust-${{ matrix.abi }}-${{ hashFiles('**/Cargo.toml', '**/Cargo.lock', '**/*.rs') }}
  
  integration_test:
    name: Integration test
    runs-on: macos-12    
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          - abi: x86
            avd: x86
            api-level: 30
          - abi: x86_64
            avd: x86_64
            api-level: 30
          - abi: arm64-v8a
            avd: x86_64
            api-level: 30
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      
      - name: Add emulator to PATH
        run: echo "${ANDROID_SDK_ROOT}/emulator" >> $GITHUB_PATH
            
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3.3
          build-root-directory: ./android
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dev' }}
      
      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with: 
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.avd }}-api-${{ matrix.api-level }}-integ # will remove 'integ' once e2e is synced
          
      - name: Native rust cache
        id: native-rust-cache
        uses: actions/cache@v3
        with:
          path: android/app/src/main/jniLibs/${{ matrix.abi }}
          key: native-rust-${{ matrix.abi }}-${{ hashFiles('**/Cargo.toml', '**/Cargo.lock', '**/*.rs') }}
      
      - run: yarn install
      
      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        run: ./scripts/integration_tests.sh -a ${{ matrix.avd }} -s

      - name: Run integration tests
        run: ./scripts/integration_tests.sh -a ${{ matrix.abi }}
 
  e2e_test:
    name: End-to-End Test
    runs-on: macos-12
    strategy:
      matrix:
        arch: [x86_64]
        api-level: [30]
    needs: [create-timestamp, build]
    env:
      timestamp: ${{ needs.create-timestamp.outputs.timestamp }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3.3
          build-root-directory: ./android
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dev'}}
      
      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with: 
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.arch }}-api-${{ matrix.api-level }}      

      - name: Download native rust
        uses: actions/download-artifact@v3
        with: 
          name: ${{ matrix.arch }}-${{ env.timestamp }}
          path: android/app/src/main/jniLibs/${{ matrix.arch }}
      
      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
      
      - run: yarn install
      - run: nohup yarn react-native start > "out.yarn_react_native_start" &
      
      - name: Run Detox Build
        run: yarn detox build -c android.emu.debug -n test
      - name: Run Detox Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: yarn detox test -c android.emu.debug -n test

