name: Integration test

on:
  workflow_call:
    inputs:
      timestamp:
        required: true
        type: string
      cache-key:
        required: true
        type: string

jobs:
  integration-test:
    name: Integration test
    runs-on: macos-12
    env:
      CACHE-KEY: ${{ inputs.cache-key }}
      TIMESTAMP: ${{ inputs.timestamp }}
    strategy:
      matrix:
        include:
          - abi: armeabi-v7a
            avd-arch: x86
            # api-level: 30
            # api-target: google_apis_playstore
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      
      - name: Add emulator to PATH
        run: echo "${ANDROID_SDK_ROOT}/emulator" >> $GITHUB_PATH
            
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3.3
          build-root-directory: ./android
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dev' }}
      
      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with: 
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.avd-arch }}-integ
          
      - name: Native rust cache
        uses: actions/cache@v3
        with:
          path: android/app/src/main/jniLibs/${{ matrix.abi }}
          key: native-rust-${{ matrix.abi }}-${{ env.CACHE-KEY }}
          fail-on-cache-miss: true
      
      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: ./scripts/integration_tests.sh -a ${{ matrix.avd-arch }} -s

      - name: Run integration tests
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: ./scripts/integration_tests.sh -a ${{ matrix.abi }}

      - name: Upload test reports
        if: ${{ ! cancelled() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-reports-${{ matrix.abi }}-${{ env.TIMESTAMP }}
          path: android/app/build/outputs/integration_test_reports
